name: Diwo
favicon: null
layout_spectrum: 0.9634
typography_spectrum: 0.15495
title: Diwo - Digital Workplace Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdf8f5'
    - '#e0ddca'
    - '#161d2f'
    - '#899a87'
    - '#35484c'
  brandStrength: 0.9375
  lightness: 0.9073998257517815
  saturation: 0.9122712451498955
  rhythmicContrast: 0.015842614229768515
purpose: []
